apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/workshops/overlays/parasol-insurance/00-prereqs?ref=v0.11
- https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/workshops/overlays/parasol-insurance/01-setup?ref=v0.11
- https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/workshops/overlays/parasol-insurance/instance?ref=v0.11
- https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/workshops/overlays/parasol-insurance/xx-image-cache?ref=v0.11
