apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: branding
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    # directory:
    #   recurse: true
    path: components/branding
    repoURL: https://github.com/adrezni/cluster-jump-start
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
