apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: false
  pairs:
    component: workshop

namespace: user0

resources:
- data-connection-secret.yaml
- job-setup-user.yaml
- notebook.yaml
- pvc.yaml
- quota.yaml
- ns-rb-admin.yaml
# - ns-rb-view.yaml
- ns.yaml
