apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/description: "Connects persistent storage to a notebook"
    openshift.io/display-name: Health Data
  labels:
    opendatahub.io/dashboard: "true"
  name: explore-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
