apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    spec:
      initContainers:
      - image: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:12
        name: db-init
        command:
          - /bin/bash
          - -c
          - |
            #!/bin/bash
            
            echo "hello postgres"
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: db-data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: postgres
