apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  source: https://github.com/adrezni/cluster-jump-start

labels:
- includeSelectors: false
  pairs:
    workshop: structured-data-healthcare

resources:
  - self-provisioner-crb.yaml
  - workshop-admins-group.yaml
  - workshop-users-group.yaml
