apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  source: https://github.com/adrezni/cluster-jump-start

labels:
- includeSelectors: false
  pairs:
    workshop: structured-data-healthcare

components:
  - ../../components/rhoai-for-workshops
  - ../../components/workshop-groups

resources:
  - base
  - user0
