apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../components/branding
- ../../components/ocp-htpasswd

# resources:
# - htpasswd-secret.yaml

patches:
  - path: patch-idp.yaml
    target:
      group: config.openshift.io
      kind: OAuth
      name: cluster
