name: code-assistant-config
version: 0.0.1
schema: v1
models:
  - name: "CodeLlama-7b"
    model: "codellama-7b"
    defaultCompletionOptions:
      contextLength: 128000
    provider: "openai"
    apiBase: "http://codellama-7b-svc.rhoai-code-assistant.svc.cluster.local/v1"
    apiKey: "NA"
    requestOptions:
      caBundlePath: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
      timeout: 300000
    roles:
      - chat
      - edit
      - autocomplete
      - apply
    capabilities:
    - tool_use
