apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../components/branding
- ../components/minio-w-ns-known-pw
- ../components/rhoai-for-workshops

resources:
- ../components/kueue-cluster-config

- ../components/rhoai-custom-notebooks
- ../components/pgadmin4
- ../components/web-terminal
